export const BEER_LIST_START = 'BEER_LIST_START';
export const BEER_IMAGES_START = 'BEER_IMAGES_START';

export const BEER_LIST_SUCCESS = 'BEER_LIST_SUCCESS';
export const BEER_IMAGES_SUCCESS = 'BEER_IMAGES_SUCCESS';

export const STOP_LOADING = 'STOP_LOADING';